-- Generated from lib/vocabulary/data.ts by npm run assets.
insert into public.vocabulary (id,hanzi,pinyin,meaning_en,meaning_id,characters,example_hanzi,example_pinyin,example_meaning_en,example_meaning_id,level,sort_order) values
('f1-001','我','wǒ','I / me','saya',ARRAY['我'],'我是学生。','Wǒ shì xuésheng.','I am a student.','Saya seorang pelajar.',1,1),
('f1-002','你','nǐ','you','kamu',ARRAY['你'],'你好！','Nǐ hǎo!','Hello!','Halo!',1,2),
('f1-003','他','tā','he / him','dia (laki-laki)',ARRAY['他'],'他是老师。','Tā shì lǎoshī.','He is a teacher.','Dia seorang guru.',1,3),
('f1-004','人','rén','person / people','orang / manusia',ARRAY['人'],'中国人','Zhōngguó rén','Chinese person','orang Tiongkok',1,4),
('f1-005','是','shì','to be','adalah',ARRAY['是'],'我是老师。','Wǒ shì lǎoshī.','I am a teacher.','Saya seorang guru.',1,5),
('f1-006','不','bù','not / no','tidak',ARRAY['不'],'我不喝咖啡。','Wǒ bù hē kāfēi.','I do not drink coffee.','Saya tidak minum kopi.',1,6),
('f1-007','有','yǒu','to have / there is','punya / ada',ARRAY['有'],'我有书。','Wǒ yǒu shū.','I have books.','Saya punya buku.',1,7),
('f1-008','好','hǎo','good / well','baik / bagus',ARRAY['好'],'很好。','Hěn hǎo.','Very good.','Sangat bagus.',1,8),
('f1-009','大','dà','big','besar',ARRAY['大'],NULL,NULL,NULL,NULL,1,9),
('f1-010','小','xiǎo','small','kecil',ARRAY['小'],NULL,NULL,NULL,NULL,1,10),
('f1-011','一','yī','one','satu',ARRAY['一'],NULL,NULL,NULL,NULL,1,11),
('f1-012','二','èr','two','dua',ARRAY['二'],NULL,NULL,NULL,NULL,1,12),
('f1-013','三','sān','three','tiga',ARRAY['三'],NULL,NULL,NULL,NULL,1,13),
('f1-014','这','zhè','this','ini',ARRAY['这'],NULL,NULL,NULL,NULL,1,14),
('f1-015','那','nà','that','itu',ARRAY['那'],NULL,NULL,NULL,NULL,1,15),
('f1-016','什么','shénme','what','apa',ARRAY['什','么'],'这是什么？','Zhè shì shénme?','What is this?','Ini apa?',1,16),
('f1-017','谁','shéi','who','siapa',ARRAY['谁'],'他是谁？','Tā shì shéi?','Who is he?','Siapa dia?',1,17),
('f1-018','哪里','nǎlǐ','where','di mana',ARRAY['哪','里'],'学校在哪里？','Xuéxiào zài nǎlǐ?','Where is the school?','Di mana sekolahnya?',1,18),
('f1-019','吃','chī','to eat','makan',ARRAY['吃'],'我吃米饭。','Wǒ chī mǐfàn.','I eat rice.','Saya makan nasi.',1,19),
('f1-020','喝','hē','to drink','minum',ARRAY['喝'],'我喝水。','Wǒ hē shuǐ.','I drink water.','Saya minum air.',1,20),
('f1-021','水','shuǐ','water','air',ARRAY['水'],'我想喝水。','Wǒ xiǎng hē shuǐ.','I want to drink water.','Saya ingin minum air.',1,21),
('f1-022','饭','fàn','cooked rice / meal','nasi / makanan',ARRAY['饭'],NULL,NULL,NULL,NULL,1,22),
('f1-023','她','tā','she / her','dia (perempuan)',ARRAY['她'],NULL,NULL,NULL,NULL,1,23),
('f1-024','我们','wǒmen','we / us','kami / kita',ARRAY['我','们'],NULL,NULL,NULL,NULL,1,24),
('f1-025','你们','nǐmen','you (plural)','kalian',ARRAY['你','们'],NULL,NULL,NULL,NULL,1,25),
('f1-026','他们','tāmen','they / them','mereka',ARRAY['他','们'],NULL,NULL,NULL,NULL,1,26),
('f1-027','你好','nǐ hǎo','hello','halo',ARRAY['你','好'],NULL,NULL,NULL,NULL,1,27),
('f1-028','谢谢','xièxie','thank you','terima kasih',ARRAY['谢','谢'],'谢谢你！','Xièxie nǐ!','Thank you!','Terima kasih!',1,28),
('f1-029','再见','zàijiàn','goodbye','sampai jumpa',ARRAY['再','见'],NULL,NULL,NULL,NULL,1,29),
('f1-030','请','qǐng','please / to invite','silakan / mengundang',ARRAY['请'],NULL,NULL,NULL,NULL,1,30),
('f1-031','对不起','duìbuqǐ','sorry','maaf',ARRAY['对','不','起'],NULL,NULL,NULL,NULL,1,31),
('f1-032','没关系','méi guānxi','it’s okay / no problem','tidak apa-apa',ARRAY['没','关','系'],NULL,NULL,NULL,NULL,1,32),
('f1-033','的','de','possessive particle','partikel kepemilikan',ARRAY['的'],NULL,NULL,NULL,NULL,1,33),
('f1-034','吗','ma','yes-or-no question particle','partikel pertanyaan ya/tidak',ARRAY['吗'],NULL,NULL,NULL,NULL,1,34),
('f1-035','在','zài','at / in / to be located','di / berada',ARRAY['在'],NULL,NULL,NULL,NULL,1,35),
('f1-036','和','hé','and / with','dan / dengan',ARRAY['和'],NULL,NULL,NULL,NULL,1,36),
('f1-037','也','yě','also / too','juga',ARRAY['也'],NULL,NULL,NULL,NULL,1,37),
('f1-038','都','dōu','all / both','semua / keduanya',ARRAY['都'],NULL,NULL,NULL,NULL,1,38),
('f1-039','没有','méiyǒu','not have / there is not','tidak punya / tidak ada',ARRAY['没','有'],NULL,NULL,NULL,NULL,1,39),
('f1-040','很','hěn','very','sangat',ARRAY['很'],NULL,NULL,NULL,NULL,1,40),
('f1-041','四','sì','four','empat',ARRAY['四'],NULL,NULL,NULL,NULL,1,41),
('f1-042','五','wǔ','five','lima',ARRAY['五'],NULL,NULL,NULL,NULL,1,42),
('f1-043','六','liù','six','enam',ARRAY['六'],NULL,NULL,NULL,NULL,1,43),
('f1-044','七','qī','seven','tujuh',ARRAY['七'],NULL,NULL,NULL,NULL,1,44),
('f1-045','八','bā','eight','delapan',ARRAY['八'],NULL,NULL,NULL,NULL,1,45),
('f1-046','九','jiǔ','nine','sembilan',ARRAY['九'],NULL,NULL,NULL,NULL,1,46),
('f1-047','十','shí','ten','sepuluh',ARRAY['十'],NULL,NULL,NULL,NULL,1,47),
('f1-048','零','líng','zero','nol',ARRAY['零'],NULL,NULL,NULL,NULL,1,48),
('f1-049','个','gè','general measure word','kata penggolong umum',ARRAY['个'],NULL,NULL,NULL,NULL,1,49),
('f1-050','两','liǎng','two (before measure words)','dua (sebelum kata penggolong)',ARRAY['两'],NULL,NULL,NULL,NULL,1,50),
('f1-051','去','qù','to go','pergi',ARRAY['去'],NULL,NULL,NULL,NULL,1,51),
('f1-052','来','lái','to come','datang',ARRAY['来'],NULL,NULL,NULL,NULL,1,52),
('f1-053','看','kàn','to look / to watch / to read','melihat / menonton / membaca',ARRAY['看'],NULL,NULL,NULL,NULL,1,53),
('f1-054','听','tīng','to listen','mendengarkan',ARRAY['听'],NULL,NULL,NULL,NULL,1,54),
('f1-055','说','shuō','to speak / to say','berbicara / mengatakan',ARRAY['说'],NULL,NULL,NULL,NULL,1,55),
('f1-056','读','dú','to read','membaca',ARRAY['读'],NULL,NULL,NULL,NULL,1,56),
('f1-057','写','xiě','to write','menulis',ARRAY['写'],NULL,NULL,NULL,NULL,1,57),
('f1-058','学习','xuéxí','to study / to learn','belajar',ARRAY['学','习'],NULL,NULL,NULL,NULL,1,58),
('f1-059','喜欢','xǐhuan','to like','suka',ARRAY['喜','欢'],'我喜欢茶。','Wǒ xǐhuan chá.','I like tea.','Saya suka teh.',1,59),
('f1-060','想','xiǎng','to want / to think','ingin / berpikir',ARRAY['想'],NULL,NULL,NULL,NULL,1,60),
('f1-061','要','yào','to want / to need','mau / perlu',ARRAY['要'],NULL,NULL,NULL,NULL,1,61),
('f1-062','买','mǎi','to buy','membeli',ARRAY['买'],NULL,NULL,NULL,NULL,1,62),
('f1-063','做','zuò','to do / to make','melakukan / membuat',ARRAY['做'],NULL,NULL,NULL,NULL,1,63),
('f1-064','叫','jiào','to be called / to call','bernama / memanggil',ARRAY['叫'],NULL,NULL,NULL,NULL,1,64),
('f1-065','知道','zhīdào','to know (a fact)','tahu',ARRAY['知','道'],NULL,NULL,NULL,NULL,1,65),
('f1-066','会','huì','can / know how to','bisa / mampu',ARRAY['会'],NULL,NULL,NULL,NULL,1,66),
('f1-067','多','duō','many / much','banyak',ARRAY['多'],NULL,NULL,NULL,NULL,1,67),
('f1-068','少','shǎo','few / little','sedikit',ARRAY['少'],NULL,NULL,NULL,NULL,1,68),
('f1-069','热','rè','hot','panas',ARRAY['热'],NULL,NULL,NULL,NULL,1,69),
('f1-070','冷','lěng','cold','dingin',ARRAY['冷'],NULL,NULL,NULL,NULL,1,70),
('f1-071','忙','máng','busy','sibuk',ARRAY['忙'],NULL,NULL,NULL,NULL,1,71),
('f1-072','高兴','gāoxìng','happy / glad','senang / gembira',ARRAY['高','兴'],NULL,NULL,NULL,NULL,1,72),
('f1-073','茶','chá','tea','teh',ARRAY['茶'],NULL,NULL,NULL,NULL,1,73),
('f1-074','咖啡','kāfēi','coffee','kopi',ARRAY['咖','啡'],NULL,NULL,NULL,NULL,1,74),
('f1-075','米饭','mǐfàn','cooked rice','nasi',ARRAY['米','饭'],NULL,NULL,NULL,NULL,1,75),
('f1-076','面条','miàntiáo','noodles','mi',ARRAY['面','条'],NULL,NULL,NULL,NULL,1,76),
('f1-077','水果','shuǐguǒ','fruit','buah',ARRAY['水','果'],NULL,NULL,NULL,NULL,1,77),
('f1-078','苹果','píngguǒ','apple','apel',ARRAY['苹','果'],NULL,NULL,NULL,NULL,1,78),
('f1-079','今天','jīntiān','today','hari ini',ARRAY['今','天'],'今天很热。','Jīntiān hěn rè.','It is hot today.','Hari ini panas.',1,79),
('f1-080','明天','míngtiān','tomorrow','besok',ARRAY['明','天'],NULL,NULL,NULL,NULL,1,80),
('f1-081','昨天','zuótiān','yesterday','kemarin',ARRAY['昨','天'],NULL,NULL,NULL,NULL,1,81),
('f1-082','现在','xiànzài','now','sekarang',ARRAY['现','在'],NULL,NULL,NULL,NULL,1,82),
('f1-083','时候','shíhou','time / moment','waktu / saat',ARRAY['时','候'],NULL,NULL,NULL,NULL,1,83),
('f1-084','年','nián','year','tahun',ARRAY['年'],NULL,NULL,NULL,NULL,1,84),
('f1-085','月','yuè','month / moon','bulan',ARRAY['月'],NULL,NULL,NULL,NULL,1,85),
('f1-086','家','jiā','home / family','rumah / keluarga',ARRAY['家'],NULL,NULL,NULL,NULL,1,86),
('f1-087','学校','xuéxiào','school','sekolah',ARRAY['学','校'],NULL,NULL,NULL,NULL,1,87),
('f1-088','商店','shāngdiàn','shop / store','toko',ARRAY['商','店'],NULL,NULL,NULL,NULL,1,88),
('f1-089','中国','Zhōngguó','China','Tiongkok',ARRAY['中','国'],NULL,NULL,NULL,NULL,1,89),
('f1-090','朋友','péngyou','friend','teman',ARRAY['朋','友'],NULL,NULL,NULL,NULL,1,90),
('f1-091','老师','lǎoshī','teacher','guru',ARRAY['老','师'],NULL,NULL,NULL,NULL,1,91),
('f1-092','学生','xuésheng','student','murid / pelajar',ARRAY['学','生'],NULL,NULL,NULL,NULL,1,92),
('f1-093','妈妈','māma','mom','ibu',ARRAY['妈','妈'],NULL,NULL,NULL,NULL,1,93),
('f1-094','爸爸','bàba','dad','ayah',ARRAY['爸','爸'],NULL,NULL,NULL,NULL,1,94),
('f1-095','名字','míngzi','name','nama',ARRAY['名','字'],NULL,NULL,NULL,NULL,1,95),
('f1-096','书','shū','book','buku',ARRAY['书'],NULL,NULL,NULL,NULL,1,96),
('f1-097','手机','shǒujī','mobile phone','ponsel',ARRAY['手','机'],NULL,NULL,NULL,NULL,1,97),
('f1-098','钱','qián','money','uang',ARRAY['钱'],NULL,NULL,NULL,NULL,1,98),
('f1-099','多少','duōshao','how many / how much','berapa',ARRAY['多','少'],'多少钱？','Duōshao qián?','How much does it cost?','Berapa harganya?',1,99),
('f1-100','怎么','zěnme','how','bagaimana',ARRAY['怎','么'],'这个字怎么读？','Zhège zì zěnme dú?','How do you read this character?','Bagaimana cara membaca karakter ini?',1,100)
on conflict (id) do update set hanzi=excluded.hanzi,pinyin=excluded.pinyin,meaning_en=excluded.meaning_en,meaning_id=excluded.meaning_id,characters=excluded.characters,example_hanzi=excluded.example_hanzi,example_pinyin=excluded.example_pinyin,example_meaning_en=excluded.example_meaning_en,example_meaning_id=excluded.example_meaning_id,sort_order=excluded.sort_order;
