import type { Vocabulary } from "@/types";
// Dictionary forms use lexical tones; spoken tone sandhi is handled by Mandarin speech.
const rows = [
  ["我", "wǒ", "I / me", "saya"],
  ["你", "nǐ", "you", "kamu"],
  ["他", "tā", "he / him", "dia (laki-laki)"],
  ["人", "rén", "person / people", "orang / manusia"],
  ["是", "shì", "to be", "adalah"],
  ["不", "bù", "not / no", "tidak"],
  ["有", "yǒu", "to have / there is", "punya / ada"],
  ["好", "hǎo", "good / well", "baik / bagus"],
  ["大", "dà", "big", "besar"],
  ["小", "xiǎo", "small", "kecil"],
  ["一", "yī", "one", "satu"],
  ["二", "èr", "two", "dua"],
  ["三", "sān", "three", "tiga"],
  ["这", "zhè", "this", "ini"],
  ["那", "nà", "that", "itu"],
  ["什么", "shénme", "what", "apa"],
  ["谁", "shéi", "who", "siapa"],
  ["哪里", "nǎlǐ", "where", "di mana"],
  ["吃", "chī", "to eat", "makan"],
  ["喝", "hē", "to drink", "minum"],
  ["水", "shuǐ", "water", "air"],
  ["饭", "fàn", "cooked rice / meal", "nasi / makanan"],
  ["她", "tā", "she / her", "dia (perempuan)"],
  ["我们", "wǒmen", "we / us", "kami / kita"],
  ["你们", "nǐmen", "you (plural)", "kalian"],
  ["他们", "tāmen", "they / them", "mereka"],
  ["你好", "nǐ hǎo", "hello", "halo"],
  ["谢谢", "xièxie", "thank you", "terima kasih"],
  ["再见", "zàijiàn", "goodbye", "sampai jumpa"],
  ["请", "qǐng", "please / to invite", "silakan / mengundang"],
  ["对不起", "duìbuqǐ", "sorry", "maaf"],
  ["没关系", "méi guānxi", "it’s okay / no problem", "tidak apa-apa"],
  ["的", "de", "possessive particle", "partikel kepemilikan"],
  ["吗", "ma", "yes-or-no question particle", "partikel pertanyaan ya/tidak"],
  ["在", "zài", "at / in / to be located", "di / berada"],
  ["和", "hé", "and / with", "dan / dengan"],
  ["也", "yě", "also / too", "juga"],
  ["都", "dōu", "all / both", "semua / keduanya"],
  ["没有", "méiyǒu", "not have / there is not", "tidak punya / tidak ada"],
  ["很", "hěn", "very", "sangat"],
  ["四", "sì", "four", "empat"],
  ["五", "wǔ", "five", "lima"],
  ["六", "liù", "six", "enam"],
  ["七", "qī", "seven", "tujuh"],
  ["八", "bā", "eight", "delapan"],
  ["九", "jiǔ", "nine", "sembilan"],
  ["十", "shí", "ten", "sepuluh"],
  ["零", "líng", "zero", "nol"],
  ["个", "gè", "general measure word", "kata penggolong umum"],
  [
    "两",
    "liǎng",
    "two (before measure words)",
    "dua (sebelum kata penggolong)",
  ],
  ["去", "qù", "to go", "pergi"],
  ["来", "lái", "to come", "datang"],
  ["看", "kàn", "to look / to watch / to read", "melihat / menonton / membaca"],
  ["听", "tīng", "to listen", "mendengarkan"],
  ["说", "shuō", "to speak / to say", "berbicara / mengatakan"],
  ["读", "dú", "to read", "membaca"],
  ["写", "xiě", "to write", "menulis"],
  ["学习", "xuéxí", "to study / to learn", "belajar"],
  ["喜欢", "xǐhuan", "to like", "suka"],
  ["想", "xiǎng", "to want / to think", "ingin / berpikir"],
  ["要", "yào", "to want / to need", "mau / perlu"],
  ["买", "mǎi", "to buy", "membeli"],
  ["做", "zuò", "to do / to make", "melakukan / membuat"],
  ["叫", "jiào", "to be called / to call", "bernama / memanggil"],
  ["知道", "zhīdào", "to know (a fact)", "tahu"],
  ["会", "huì", "can / know how to", "bisa / mampu"],
  ["多", "duō", "many / much", "banyak"],
  ["少", "shǎo", "few / little", "sedikit"],
  ["热", "rè", "hot", "panas"],
  ["冷", "lěng", "cold", "dingin"],
  ["忙", "máng", "busy", "sibuk"],
  ["高兴", "gāoxìng", "happy / glad", "senang / gembira"],
  ["茶", "chá", "tea", "teh"],
  ["咖啡", "kāfēi", "coffee", "kopi"],
  ["米饭", "mǐfàn", "cooked rice", "nasi"],
  ["面条", "miàntiáo", "noodles", "mi"],
  ["水果", "shuǐguǒ", "fruit", "buah"],
  ["苹果", "píngguǒ", "apple", "apel"],
  ["今天", "jīntiān", "today", "hari ini"],
  ["明天", "míngtiān", "tomorrow", "besok"],
  ["昨天", "zuótiān", "yesterday", "kemarin"],
  ["现在", "xiànzài", "now", "sekarang"],
  ["时候", "shíhou", "time / moment", "waktu / saat"],
  ["年", "nián", "year", "tahun"],
  ["月", "yuè", "month / moon", "bulan"],
  ["家", "jiā", "home / family", "rumah / keluarga"],
  ["学校", "xuéxiào", "school", "sekolah"],
  ["商店", "shāngdiàn", "shop / store", "toko"],
  ["中国", "Zhōngguó", "China", "Tiongkok"],
  ["朋友", "péngyou", "friend", "teman"],
  ["老师", "lǎoshī", "teacher", "guru"],
  ["学生", "xuésheng", "student", "murid / pelajar"],
  ["妈妈", "māma", "mom", "ibu"],
  ["爸爸", "bàba", "dad", "ayah"],
  ["名字", "míngzi", "name", "nama"],
  ["书", "shū", "book", "buku"],
  ["手机", "shǒujī", "mobile phone", "ponsel"],
  ["钱", "qián", "money", "uang"],
  ["多少", "duōshao", "how many / how much", "berapa"],
  ["怎么", "zěnme", "how", "bagaimana"],
] as const;
const examples: Record<string, [string, string, string, string]> = {
  我: [
    "我是学生。",
    "Wǒ shì xuésheng.",
    "I am a student.",
    "Saya seorang pelajar.",
  ],
  你: ["你好！", "Nǐ hǎo!", "Hello!", "Halo!"],
  他: ["他是老师。", "Tā shì lǎoshī.", "He is a teacher.", "Dia seorang guru."],
  人: ["中国人", "Zhōngguó rén", "Chinese person", "orang Tiongkok"],
  是: ["我是老师。", "Wǒ shì lǎoshī.", "I am a teacher.", "Saya seorang guru."],
  不: [
    "我不喝咖啡。",
    "Wǒ bù hē kāfēi.",
    "I do not drink coffee.",
    "Saya tidak minum kopi.",
  ],
  有: ["我有书。", "Wǒ yǒu shū.", "I have books.", "Saya punya buku."],
  好: ["很好。", "Hěn hǎo.", "Very good.", "Sangat bagus."],
  吃: ["我吃米饭。", "Wǒ chī mǐfàn.", "I eat rice.", "Saya makan nasi."],
  喝: ["我喝水。", "Wǒ hē shuǐ.", "I drink water.", "Saya minum air."],
  水: [
    "我想喝水。",
    "Wǒ xiǎng hē shuǐ.",
    "I want to drink water.",
    "Saya ingin minum air.",
  ],
  什么: ["这是什么？", "Zhè shì shénme?", "What is this?", "Ini apa?"],
  谁: ["他是谁？", "Tā shì shéi?", "Who is he?", "Siapa dia?"],
  哪里: [
    "学校在哪里？",
    "Xuéxiào zài nǎlǐ?",
    "Where is the school?",
    "Di mana sekolahnya?",
  ],
  谢谢: ["谢谢你！", "Xièxie nǐ!", "Thank you!", "Terima kasih!"],
  喜欢: ["我喜欢茶。", "Wǒ xǐhuan chá.", "I like tea.", "Saya suka teh."],
  今天: [
    "今天很热。",
    "Jīntiān hěn rè.",
    "It is hot today.",
    "Hari ini panas.",
  ],
  多少: [
    "多少钱？",
    "Duōshao qián?",
    "How much does it cost?",
    "Berapa harganya?",
  ],
  怎么: [
    "这个字怎么读？",
    "Zhège zì zěnme dú?",
    "How do you read this character?",
    "Bagaimana cara membaca karakter ini?",
  ],
};
export const vocabulary: Vocabulary[] = rows.map(
  ([hanzi, pinyin, meaningEn, meaningId], i) => ({
    id: `f1-${String(i + 1).padStart(3, "0")}`,
    hanzi,
    pinyin,
    meaningEn,
    meaningId,
    characters: Array.from(hanzi),
    level: 1,
    order: i + 1,
    ...(examples[hanzi]
      ? {
          exampleHanzi: examples[hanzi][0],
          examplePinyin: examples[hanzi][1],
          exampleMeaningEn: examples[hanzi][2],
          exampleMeaningId: examples[hanzi][3],
        }
      : {}),
  }),
);
export const milestones = [
  { name: "Foundation 1", total: 100, available: true },
  { name: "Foundation 2", total: 250, available: false },
  { name: "Foundation 3", total: 500, available: false },
  { name: "Foundation 4", total: 1000, available: false },
];
