export type BopomofoSymbol = {
  symbol: string;
  pinyin: string;
  tip: string;
  example: string;
  zhuyin: string;
  examplePinyin: string;
  meaning: string;
  meaningId: string;
};
// Order follows the MOE's 37-symbol chart; Pinyin here is a sound correspondence,
// not the English letter name. Examples are syllables, not isolated consonants.
const rows = [
  [
    "ㄅ",
    "b",
    "Close both lips, then release with little puff of air.",
    "八",
    "ㄅㄚ",
    "bā",
    "eight",
    "delapan",
  ],
  [
    "ㄆ",
    "p",
    "Same lip position as ㄅ, with a clear puff of air.",
    "怕",
    "ㄆㄚˋ",
    "pà",
    "afraid",
    "takut",
  ],
  [
    "ㄇ",
    "m",
    "Keep your lips together; let the sound hum through your nose.",
    "妈",
    "ㄇㄚ",
    "mā",
    "mother",
    "ibu",
  ],
  [
    "ㄈ",
    "f",
    "Let air pass between your upper teeth and lower lip.",
    "饭",
    "ㄈㄢˋ",
    "fàn",
    "rice / meal",
    "nasi / makanan",
  ],
  [
    "ㄉ",
    "d",
    "Tongue near the ridge behind the upper teeth; release with little air.",
    "大",
    "ㄉㄚˋ",
    "dà",
    "big",
    "besar",
  ],
  [
    "ㄊ",
    "t",
    "Use the ㄉ tongue position, but release a puff of air.",
    "他",
    "ㄊㄚ",
    "tā",
    "he",
    "dia (laki-laki)",
  ],
  [
    "ㄋ",
    "n",
    "Tongue touches behind the upper teeth; sound passes through the nose.",
    "你",
    "ㄋㄧˇ",
    "nǐ",
    "you",
    "kamu",
  ],
  [
    "ㄌ",
    "l",
    "Tongue touches behind the upper teeth; air passes around its sides.",
    "来",
    "ㄌㄞˊ",
    "lái",
    "come",
    "datang",
  ],
  [
    "ㄍ",
    "g",
    "Raise the back of your tongue; release with little air.",
    "狗",
    "ㄍㄡˇ",
    "gǒu",
    "dog",
    "anjing",
  ],
  [
    "ㄎ",
    "k",
    "Like ㄍ, with a stronger puff of air.",
    "看",
    "ㄎㄢˋ",
    "kàn",
    "look / watch",
    "melihat",
  ],
  [
    "ㄏ",
    "h",
    "Let air rub past the back of the tongue; listen to the recording.",
    "好",
    "ㄏㄠˇ",
    "hǎo",
    "good",
    "baik",
  ],
  [
    "ㄐ",
    "j",
    "Keep the tongue tip down and raise its front toward the hard palate. Little puff.",
    "鸡",
    "ㄐㄧ",
    "jī",
    "chicken",
    "ayam",
  ],
  [
    "ㄑ",
    "q",
    "Same position as ㄐ, with a puff. It is not the English q sound.",
    "七",
    "ㄑㄧ",
    "qī",
    "seven",
    "tujuh",
  ],
  [
    "ㄒ",
    "x",
    "Same tongue area as ㄐ and ㄑ; let air flow continuously.",
    "西",
    "ㄒㄧ",
    "xī",
    "west",
    "barat",
  ],
  [
    "ㄓ",
    "zh",
    "Raise the tongue tip toward the roof, farther back than ㄗ. Little puff.",
    "知",
    "ㄓ",
    "zhī",
    "know",
    "tahu",
  ],
  [
    "ㄔ",
    "ch",
    "Use the ㄓ position with a puff of air.",
    "吃",
    "ㄔ",
    "chī",
    "eat",
    "makan",
  ],
  [
    "ㄕ",
    "sh",
    "Raise the tongue tip; let air flow without an initial stop.",
    "是",
    "ㄕˋ",
    "shì",
    "be / is",
    "adalah",
  ],
  [
    "ㄖ",
    "r",
    "Use a raised tongue tip and voice the sound. Mandarin r differs from English r.",
    "人",
    "ㄖㄣˊ",
    "rén",
    "person",
    "orang",
  ],
  [
    "ㄗ",
    "z",
    "Tongue near the teeth; a brief stop then friction, with little puff.",
    "字",
    "ㄗˋ",
    "zì",
    "written character",
    "aksara",
  ],
  [
    "ㄘ",
    "c",
    "Same position as ㄗ, with a puff. Not the English k or s reading of c.",
    "次",
    "ㄘˋ",
    "cì",
    "time / occurrence",
    "kali",
  ],
  [
    "ㄙ",
    "s",
    "Keep the tongue near the teeth and let air flow continuously.",
    "四",
    "ㄙˋ",
    "sì",
    "four",
    "empat",
  ],
  [
    "ㄚ",
    "a",
    "Open your mouth for a clear a vowel.",
    "啊",
    "ㄚ",
    "ā",
    "ah",
    "ah",
  ],
  [
    "ㄛ",
    "o",
    "Round your lips. Listen to its sound after ㄅ in 波.",
    "波",
    "ㄅㄛ",
    "bō",
    "wave",
    "gelombang",
  ],
  [
    "ㄜ",
    "e",
    "Keep the lips unrounded; this is the vowel in 喝, not English ee.",
    "喝",
    "ㄏㄜ",
    "hē",
    "drink",
    "minum",
  ],
  [
    "ㄝ",
    "ê / e after i or ü",
    "A more open, front vowel than ㄜ. Often heard in ㄧㄝ and ㄩㄝ.",
    "也",
    "ㄧㄝˇ",
    "yě",
    "also",
    "juga",
  ],
  [
    "ㄞ",
    "ai",
    "Glide from a toward i within one syllable.",
    "爱",
    "ㄞˋ",
    "ài",
    "love",
    "cinta",
  ],
  [
    "ㄟ",
    "ei",
    "Glide toward i; keep it one syllable.",
    "黑",
    "ㄏㄟ",
    "hēi",
    "black",
    "hitam",
  ],
  [
    "ㄠ",
    "ao",
    "Start open, then round the lips as the sound closes.",
    "好",
    "ㄏㄠˇ",
    "hǎo",
    "good",
    "baik",
  ],
  [
    "ㄡ",
    "ou",
    "Glide from o toward u within one syllable.",
    "口",
    "ㄎㄡˇ",
    "kǒu",
    "mouth",
    "mulut",
  ],
  [
    "ㄢ",
    "an",
    "Finish with the tongue tip touching behind the upper teeth: n.",
    "三",
    "ㄙㄢ",
    "sān",
    "three",
    "tiga",
  ],
  [
    "ㄣ",
    "en",
    "A central vowel ending in n. After ㄧ or ㄩ, Pinyin uses in or ün.",
    "人",
    "ㄖㄣˊ",
    "rén",
    "person",
    "orang",
  ],
  [
    "ㄤ",
    "ang",
    "Finish with the back of the tongue raised: ng. Do not add a g release.",
    "忙",
    "ㄇㄤˊ",
    "máng",
    "busy",
    "sibuk",
  ],
  [
    "ㄥ",
    "eng",
    "A central vowel ending in ng. Its sound adjusts after a medial.",
    "风",
    "ㄈㄥ",
    "fēng",
    "wind",
    "angin",
  ],
  [
    "ㄦ",
    "er",
    "A vowel with an r-like ending. It can form a syllable on its own.",
    "二",
    "ㄦˋ",
    "èr",
    "two",
    "dua",
  ],
  [
    "ㄧ",
    "i",
    "A high front vowel with unrounded lips. On its own, Pinyin writes yi.",
    "一",
    "ㄧ",
    "yī",
    "one",
    "satu",
  ],
  [
    "ㄨ",
    "u",
    "A high back vowel with rounded lips. On its own, Pinyin writes wu.",
    "五",
    "ㄨˇ",
    "wǔ",
    "five",
    "lima",
  ],
  [
    "ㄩ",
    "ü",
    "Start with the tongue position for i, then round your lips without moving the tongue back.",
    "女",
    "ㄋㄩˇ",
    "nǚ",
    "female / woman",
    "perempuan",
  ],
] as const;
export const symbols: BopomofoSymbol[] = rows.map(
  ([
    symbol,
    pinyin,
    tip,
    example,
    zhuyin,
    examplePinyin,
    meaning,
    meaningId,
  ]) => ({
    symbol,
    pinyin,
    tip,
    example,
    zhuyin,
    examplePinyin,
    meaning,
    meaningId,
  }),
);
export const symbolAsset = (symbol: string, ext: "json" | "wav") =>
  `/bopomofo/${symbol.codePointAt(0)!.toString(16)}.${ext}`;
export const bopomofoSources = [
  {
    title: "Taiwan Ministry of Education · Bopomofo manual",
    url: "https://language.moe.gov.tw/001/Upload/files/site_content/M0001/juyin/html_en/index.html",
  },
  {
    title: "MOE audio and stroke assets · CC BY 4.0",
    url: "https://language.moe.gov.tw/001/Upload/files/site_content/M0001/juyin/",
  },
  {
    title: "MIT OpenCourseWare · Mandarin sounds and Pinyin",
    url: "https://ocw.mit.edu/courses/res-21g-003-learning-chinese-a-foundation-course-in-mandarin-spring-2011/",
  },
];
